resources/graphql/crdc-datahub.graphql
routers/graphql-router.js
services/approved-studies.js

This PR introduces backend support for the Approved Studies dropdown on the frontend. It's an extension to `listApprovedStudies`, and filters the results to only studies assigned to an organization.
Notes:
- ~~The GraphQL schema was updated~~ See PR #104
- `listApprovedStudies` is converted to an admin only OP
- The Postman collection has been updated to include this new API
- There is no submodule update for this PR
https://tracker.nci.nih.gov/browse/CRDCDH-474
https://tracker.nci.nih.gov/browse/CRDCDH-159

CRDCDH-474 `listApprovedStudiesOfMyOrganization`

---

constants/submission-constants.js
services/submission.js

update submission statuses as fronted requires more statuses to be available.

update submission statuses

---

services/submission.js

Previously, I assumed the User role would never have submissions to view, so allowing them to see their own submissions was fine, (they can't create submissions, so they wont see any).
However, if they create submissions, then have their role changed by an admin back to user, they will still be able to see their  previously created submissions. 
This is just a more airtight way to adhere to requireents.

fix user role results for listSubmissions

---

services/aws-request.js
services/submission.js

Log file format will changed to ZIP.  To make listLogs API to match the change, following logics are added:
1) check if there are zip files in the log dir.  if existing, return last zip file,  otherwise go to 2)
2) check if there are .log files in the log dir, if existing, return last .log file, otherwise return empty array.

Update listLogs for file type change.

---

services/submission.js

This pr makes dbgapID optional for creating a data submission, as required by ticket 606

make dbgap optional for creating a data submission

---

services/submission.js

Per changing requirements, this PR removes ICDC from M2 backend acceptable data commons list.
N/A
https://tracker.nci.nih.gov/browse/CRDCDH-680
> [!IMPORTANT]  
> This is a fix for M2 only, and should not be merged with the Milestone 3 branch until we receive further information from K.C.

CRDCDH-680 Remove ICDC from M2

---

services/batch-service.js
services/submission.js

1.  Don't update metadataValidationStatus of submission to "New", let essential validator service do.
2.  Don't update batch status to "Uploaded" after tsv files are uploaded into s3 bucket.  Let essential validator to do so.

Crdcdh 736 001 pgu

---

services/data-record-service.js

- Remove nodeType secondary sort if primary sort is nodeType
- Lock secondary sort direction to ascending regardless of primary sort direction

Update secondary sort direction

---

constants/error-constants.js
services/application.js

Since it requires to remove the uniqueness constraint for study abbreviations, it cannot automatically update an abbreviation change within the organization's collection. We need to manually ensure that the study abbreviations are updated in the organization collection if they are altered.

CRDCDH-907

---

services/data-record-service.js

remove non-object type (non-validation string) errors from the submission.fileErrors and submission.fileWarnings arrays before parsing

filter submission fileErrors

---

constants/error-constants.js
services/data-record-service.js
services/submission.js

The logics for validate both are modified.  Before, validation is sequentially, metadata request is sent first, if failed, return the error so the file validation call is skipped.  After modification,  both metadata and file will be validated then return.

Update validation submission logics.

---

resources/graphql/crdc-datahub.graphql
services/data-record-service.js

Read cross-submission errors stored in DataRecord.additional_errors and include them in the submissionQCResults API

CRDCDH-998

---

services/submission.js

Hi Young,  during integration testing for crdcdh-1233, found the validation record is not saved to db before send message,  after sent, a new validation record with new _id is inserted to DB.  This caused the validator can't find the validation with the id passed via sqs message,   I fixed the issue and works now.  Please review.

fix validation record issue.

---

.gitignore
resources/graphql/crdc-datahub.graphql
services/application.js
services/approved-studies.js
services/submission.js

This PR updates the Submission Request functionality to support an additional (optional) `ORCID` field provided by the frontend. When provided, this field is stored within the ApprovedStudy collection during application approval. This PR also extends the Data Submission creation functionality to populate a new property `ORCID` when the selected study has this field defined.
> [!Warning]
> This feature is for the 3.1.0 release, not 3.0.0
> [!Warning]
> This PR also depends on a drivers update in PR https://github.com/CBIIT/crdc-datahub-database-drivers/pull/103
- Add `ORCID` to the `Submission`, `ApprovedStudy`, and `Application` types
- Update AppInput to support `ORCID` string input
- Update the approveApplication handling to pass `ORCID` to the ApprovedStudy if it's defined
- Update the …

CRDCDH-1430 Add `ORCID` Support

---

services/submission.js

Added submission status "Rejected" and "Withdrawn" to be included in the `otherSubmissions` property with the `getSubmission` API response.
N/A
[CRDCDH-1489](https://tracker.nci.nih.gov/browse/CRDCDH-1489)

CRDCDH-1489 Added additional submission statuses to otherSubmissions property

---

services/submission.js

Added an additional guard to ensure that a valid dbGaPID param is passed to createSubmission API when the study chosen has controlled access.
N/A
[CRDCDH-1545](https://tracker.nci.nih.gov/browse/CRDCDH-1545)

CRDCDH-1545 Validate dbGaPID for controlled studies when creating a submission

---

constants/error-constants.js
services/submission.js

This PR is just for updating an error message while creating a data submission. This error occurs when the user is missing a dbGaPID and chooses a study with controlled access.
N/A
[CRDCDH-1545](https://tracker.nci.nih.gov/browse/CRDCDH-1545)

CRDCDH-1545 Improved error message for missing dbGaPID when study with controlled access is selected

---

services/submission.js

Check the submission name character length without trimming the whitespace. This implementation also matches the FE as it also restricts the input to 25 characters without trimming the whitespace.
N/A
[CRDCDH-1544](https://tracker.nci.nih.gov/browse/CRDCDH-1544)

CRDCDH-1544 Check Submission name length without trimming whitespace

---

services/data-record-service.js

- CRDCDH-1539
- removed batch table join in submissionQCResults and submissionCrossValidationResults pipelines
- moved batch filtering earlier in the pipeline in submissionQCResults and submissionCrossValidationResults pipelines

validation query optimization

---

resources/graphql/crdc-datahub.graphql
routers/graphql-router.js
services/approved-studies.js

This is a quick PR to add an API endpoint to fetch a approved study by ID. This is a blocker for [CRDCDH-1485](https://tracker.nci.nih.gov/browse/CRDCDH-1485).
- Add Admin-only `getApprovedStudy` API functionality
- Update GraphQL schema accordingly
[CRDCDH-1748](https://tracker.nci.nih.gov/browse/CRDCDH-1748)

CRDCDH-1748 Create API to fetch a Approved Study by ID

---

services/submission.js

Minor PR to restore the Data Submission creation functionality. The `getOrganizationByName` call does not populate the studies field by default, but we also have the Organization ID in this context, so I swapped it out with `getOrganizationByID`. See PR #534 for context.
- Replace `createSubmission`'s call to `getOrganizationByName` with `getOrganizationByID`
CRDCDH-1853 (Bug)

HOTFIX: Organization Name lookup not returning populated studies

---

services/qc-result-service.js
services/submission.js

submissionStats API
- update origin property: "API: submissionStats"

CRDCDH-1832

---

app.js
config.js
routers/graphql-router.js
services/data-record-service.js
services/notify-user.js

- Added alternative process envs
- Replaced dependencies

CRDCDH-1839

---

resources/graphql/crdc-datahub.graphql
resources/json/PBACDefaults_config.json

This PR updates the PBACDefaults JSON file for the new `order` numerical property. It also includes updates to fix outdated names.
- Add `order` property to all PBAC options, based on [CRDCDH-1886](https://tracker.nci.nih.gov/browse/CRDCDH-1886)
- Update the outdated visual name for emails: `access:requested`, `account:inactivated`, and `account:users_inactivated`
- Update the incorrect Group Name for Email Notification `data_submission:deleted` for the `User` role
N/A – Many PBAC tickets

feat: Add `order` to PBAC Notification and Permissions

---

resources/graphql/crdc-datahub.graphql
services/approved-studies.js

Updated based on changes in user story and task as listed below:
-Update createApprovedStudy and updateApprovedStudy APIs and make primaryContactID parameter optional 
-Update ApprovedStudy GraphQL type and all APIs which returns that type and change program to programs and make is [UserOrganization]

CRDCDH 2161

---

services/approved-studies.js

Fixed by changed the logic for updating submission's conciergeName, conciergeEmail.   The existing logic skipped submission updating if study's primaryContact is set to null.

CRDCDH 2484

---

services/batch-service.js

Replace "/" in file name with "_" before save to s3 bucket when retrieving individual metadata file or zip file for all files in batch.

Fixed CRDCDH-2749

---

constants/error-constants.js
services/submission.js

Updated submission.js and error constants to enable heartbeat for metadata uploading.

Enable heartbeat for metadata

---

services/authorization-service.js

Throw an error if the input scope is not provided.

CRDCDH-2835

---

services/data-record-service.js

Minor change.  Force to use participant.nodeID for get diagnosis age that fixes the get age in case the dbGap_participant_ID is not null.

FixGetDiagnosisAge

---

services/aws-request.js

Minor change to set durationSeconds to 12 hours.  and passed testing as shown in console log:
Temporary credentials obtained successfully
Token is valid for: 12.00 hours

Make temp credential valid for 12 hr.

---

constants/error-constants.js
routers/graphql-router.js

Remove the duplicate route for downloadDBGaPLoadSheet.
Added an error constant, USER_NOT_EXIST: "The user does not exist.",

Remove duplication router

---

resources/json/PBACDefaults_config.json

Renamed the 'name' field for 'data_submission:cfg_changed' in multiple sections from 'When changed' to 'When config changed' for clarity in PBACDefaults_config.json.

Update email config name to 'When config changed'

---

resources/graphql/crdc-datahub.graphql
services/approved-studies.js
test/services/approved-studies.test.js

Make the GPAName and dbGaPID optional parameters createApprovedStudy and updateApprovedStudy. Return an error if updating or creating a study with an invalid GPAName state. If GPAName is null or empty and controlledAccess is true then isPendingGPA must be true. If this validation fails then an error is returned.

Make GPAName and dbGaPID optional parameters
