- services/application.js
- test/graphql-queries/get-my-last-application.test.js
> Last Application Status

- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/application.js
- test/graphql-queries/create-application.test.js
- test/graphql-queries/save-application.test.js
- test/test-constants.js
- removed createApplication
- automatically creates and initializes an application if no id is specified while saving and application
> Combine createApplication and saveApplication

- app.js
- routers/graphql-router.js
- services/application.js
- test/graphql-queries/batch-job.test.js
- test/graphql-queries/list-applications.test.js
- test/utility/mongodb.util.test.js
Updated
1. application sorting
2. verifying admin user roles
> List applications

- constants/error-constants.js
- services/application.js
- test/verifier/user-info-verifier.test.js
- verifier/user-info-verifier.js
- Perform a check to verify that the user has permission to review applications before allowing them to call the approve or reject API. Only the Federal Lead and Admin can review applications
> Validate user role before review

- app.js
- routers/graphql-router.js
- services/application.js
- services/organization.js
- test/graphql-queries/batch-job.test.js
- test/graphql-queries/list-applications.test.js
- test/test-constants.js
Added organization services
Added test codes
- organization services
Added organization collections
> Added organization services

- services/application.js
Deleted applications should not be listed at any time.
> Filter deleted applications

- constants/error-constants.js
- services/application.js
> remove error

- services/application.js
> fixed email template

- resources/graphql/crdc-datahub.graphql
- createSubmission
- listApprovedStudies
- listSubmissions
- getSubmission
> Submission APIs

- resources/graphql/crdc-datahub.graphql
- services/application.js
- removed ISO conversion
- used scalar Date
- date automatically converted to string
> Removed ISO Conversion

- services/application.js
- services/notify-user.js
> removed email CCs

- services/application.js
- services/notify-user.js
Removed organization owner notifications the except approval application.
> Organization Owner Notification

- Dockerfile
updated Dockerfile to use node:18.18.0
> Nodeupdate

- constants/error-constants.js
- services/application.js
prevent the duplicate study-abbreviation
> unique study-abbreviation

- app.js
- constants/error-constants.js
- routers/graphql-router.js
- services/application.js
- services/approved-studies.js
- test/graphql-queries/batch-job.test.js
- test/utility/string.util.test.js
> approved studies

- app.js
inactive user notification updated
1. the org owner will receive its disabled users.
2. admin will receive all disabled users
> Disable Inactive User Notification

- app.js
close connection pool after use
> close connection pool

- services/submission.js
adding the data commons POC filtering.
> List submissions poc role fix

- constants/submission-constants.js
- services/submission.js
Change to filter by orgID instead of orgName.
> List submissions filter by organization

- routers/graphql-router.js
> update aswservice call

- constants/submission-constants.js
- services/submission.js
re-adding submission status constants since I messed up and removed it in #109
> re-add submission constants

- constants/error-constants.js
- package-lock.json
- routers/graphql-router.js
- services/submission.js
This fully implements `createSubmission` to fufill the ticket requirements:
List of changes:
- Retrieve rootPath, concierge, and bucketName from organization backend
- Check dataCommons is within a list of approved dataCommons (the only one allowed currently is CDS).
- Ensure study abbreviation matches an approve study within the user's organization.
> fulfill createSubmission ticket requirements

- routers/graphql-router.js
- services/submission.js
> Added getSubmission 

- services/submission.js
> Updated getSubmission

- constants/submission-constants.js
- resources/graphql/crdc-datahub.graphql
- services/submission.js
This adds conciergeEmail to submissions and changes concierge to conciergeName.
This also fixes a typo where I spelled canceled as cancelled.
> add conciergeEmail to submissions

- resources/yaml/notification_email_values.yaml
- services/notify-user.js
- services/submission.js
> cancel submission notification

- constants/submission-constants.js
- package-lock.json
- services/submission.js
Fix a bug when submission action is Archive.
> Crdcdh 462 002 pgu

- resources/yaml/notification_email_values.yaml
- services/submission.js
- update spelling and fix broken constant caused by previous spelling update
> updated canceled spelling

- config.js
removed the duplicate bucket name
> Remove Duplicate Bucket-Name

- services/submission.js
This pr adds CCDI as an option for data commons parameter when creating a data submission, as required in ticket 525.
> add ccdi data common option

- services/submission.js
> Submit submisssion notification bugfix

- services/submission.js
I mistakenly PR'd these changes to 2.1 in #137. These changes should be for 2.0 as well.
> Crdcdh 525

- app.js
- config.js
- services/batch-service.js
- services/notify-user.js
Added the name of tier on the email template.
> added the tier message for user and admin

- constants/application-constants.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/application.js
- services/notify-user.js
1. Added INQUIRED constant
2. Renamed Reject => Inquire
- GraphQL APIs
- Email notification variable
> Inquire application

- constants/submission-constants.js
- verifier/submission-verifier.js
> Updated rule based on request

- services/batch-service.js
Fixed presigned url folder directory
> Presigned Folder Directory

- services/submission.js
According to updated requirements, changing ccdi to icdc.
> update data common to icdc

- services/submission.js
Log the submission status history
> Added submission history event

- verifier/submission-verifier.js
Add Data POC role for complete action.  This is new requirement change in user story after I implemented.
> Add Data POC role for complete action

- services/submission.js
> submission history could be null

- services/submission.js
[CRDCDH-624](https://tracker.nci.nih.gov/browse/CRDCDH-624)
> Update display from submitter's first name to submitter's full name

- constants/error-constants.js
- domain/batch.js
- services/batch-service.js
- services/submission.js
Rootpath needs timestamp directory
> Rootpath Timestamp

- services/submission.js
accept metadata-intention types
- update
- delete
- new
> accept metadata-intention

- resources/graphql/crdc-datahub.graphql
Added Validating status to metadataValidationStatus and fileValidationStatus
> Added Validating status to metadataValidationStatus and fileValidationStatus

- constants/error-constants.js
- constants/submission-constants.js
- resources/graphql/crdc-datahub.graphql
- services/data-record-service.js
- services/submission.js
- test/utility/validation.util.test.js
- utility/validation-handler.js
1. Renamed Error Variable
2. Updated scheme change
3. Created ValidationHandler class
4. ValidationHandler test codes
> CRDCDH-581

- Dockerfile
modified Dockefile with node update version
> modified Dockefile with node update version

- config.js
- env.template
- services/notify-user.js
Make review committee emails configurable.
1) make a new env variable, REVIEW_COMMITTEE_EMAIL;
2) enable multiple emails and separated by comma for the variable.   Please note the semi-colon is a reserved char for separate variables.
3) update notify_user.js to use the configured emails.   It use constant before.
> Crdcdh 653 001 pgu

- services/submission.js
> fixed the variable name

- services/aws-request.js
added sorting function for log files.
> add sorting func for log files

- services/data-record-service.js
Missing submissionID for filtering
> missing submissionID

- config.js
- constants/error-constants.js
- env.template
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/aws-request.js
- services/data-record-service.js
- services/submission.js
1) implemented export submission API.
2) added sorting function for logs files in s3 bucket.
> Crdcdh 703 001 pgu

- resources/graphql/crdc-datahub.graphql
Reverts CBIIT/crdc-datahub-backend#229
> Revert "missing displayID"

- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/data-record-service.js
> CRDCDH-696

- services/submission.js
- verifier/submission-verifier.js
1. store&rollback updated time
2. fileValidationStatus is allowed to be null for admin role
> CRDCDH-637

- resources/graphql/crdc-datahub.graphql
Add NodeType in FileInfo object in GraphQL schema.
> Add nodeType in FileInfo

- services/batch-service.js
disable pagination if first is -1
> CRDCDH-750

- constants/error-constants.js
- services/submission.js
1.  update the constants, NO_VALIDATION_FILE
2. updated function, #updateValidationStatus
3. add logics to handle error, NO_VALIDATION_FILE
> update fileValidationStatus to Error if no file nodes are find

- resources/graphql/crdc-datahub.graphql
- services/aws-request.js
- services/batch-service.js
- services/submission.js
1.  update UploadResult in graphql schema by add a field, skipped, as shown below
input UploadResult {
fileName: String
succeeded: Boolean
errors: [String]
skipped: Boolean
}
2.  update batch-service.js with logics for skipped files.
> Implement 749 for skipped files

- constants/submission-constants.js
- services/submission.js
Add submission status check.  Only submitted can be export.
> Crdcdh 749 001 pgu

- resources/graphql/crdc-datahub.graphql
- services/data-record-service.js
- add secondary sorting
- fix displayID
- add validation type
- add validated date
- split errors and warnings
> CRDCDH-743

- resources/graphql/crdc-datahub.graphql
- services/data-record-service.js
- add validatedDate to DataRecord in schema
- fixed lookup location for validationType property
- change secondary sort direction to match user input
> submissionQCResults updates

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- services/submission.js
- verifier/submission-verifier.js
submission reject action needs a comment
> CRDCDH-741

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- services/submission.js
- verifier/submission-verifier.js
throw an error for empty comment if admin role and meta/file error contained
> CRDCDH - 742

- services/submission.js
- verifier/submission-verifier.js
The comment should be stored in the event object instead.
> ReviewComment in the history

- config.js
- constants/error-constants.js
- routers/graphql-router.js
- services/submission.js
- services/utility.js
1. The model version should be obtained from the given URL, and it may vary depending on the tier name.
2. The new submission records the version name.
> Data Model Version

- routers/graphql-router.js
- services/data-record-service.js
groupID should be unique to enable autoscaling running in parallel
> groupID should be unique to enable autoscaling running in parallel

- services/data-record-service.js
validation should order by file size
> validation order by asc file size

- services/submission.js
DC_POC was listed in place of CURATOR in submissionQCResults API permissions
> Fix incorrect role

- services/batch-service.js
1.  change batch filePrefix from "data file" to "file"
> change batch prefix from "data file" to "file"

- Dockerfile
> updated to node:20

- constants/error-constants.js
- services/application.js
- services/approved-studies.js
Removed uniqueness of study name & study abbreviation
> CRDCDH-907

- services/submission.js
fixed updatedAT was set to null
> fix updatedAt is null issue

- services/data-record-service.js
Allow file validation even without manifest
> remove no manifest check

- app.js
Email Notification - Inactive Users 
- inactive users keep getting email notifications
> [Bug] Email Notification - Inactive Users 

- app.js
inactive users keep getting email notifications
> [Bug] Inactive User Email Notification

- resources/graphql/crdc-datahub.graphql
Submission Scheme Update
- intention
> submission change

- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/data-record-service.js
- services/submission.js
Implemented getSumissionNodes API
> Implemented getSumissionNodes API

- domain/batch.js
This reverts commit e5f252ff3e93e97ee2ef00919c07659360a3aa80.
> Revert "Update batch file nodeType in constructor"

- verifier/submission-verifier.js
a delete intention should be allowed for an submit action without the data-file requirement.
> CRDCDH-1000

- constants/error-constants.js
- services/batch-service.js
Return following error if a request tries to create a "data file" batch for a submission of "Delete" type.
> CRDCDH-986

- services/data-record-service.js
> updated getFileNodes function

- services/data-record-service.js
- if "first" param is < 1 then return all results
- split count and paged results into separate queries to avoid memory issues caused by a large result set
- update submodule
> CRDCDH-909

- resources/graphql/crdc-datahub.graphql
- services/submission.js
Added dynamic query for other submissions
> CRDCDH-997

- resources/graphql/crdc-datahub.graphql
- services/submission.js
store crossSubmissionStatus field
> CRDCDH-996

- config.js
- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- resources/yaml/data_file_upload_config.yaml
- routers/graphql-router.js
- services/submission.js
- services/utility.js
- utility/io-util.js
- verifier/user-info-verifier.js
> Implemented crdcdh-990

- constants/error-constants.js
- routers/graphql-router.js
- services/batch-service.js
- services/submission.js
replaced the origin of submission bucket name from .env to the field in the submission document.
> Submission Bucket Origin

- constants/submission-constants.js
- domain/batch.js
- services/submission.js
- verifier/batch-verifier.js
1. Removed redundant batch intention
2. Updated batch intention constant value
> CRDCDH-1097

- constants/error-constants.js
- services/submission.js
prohibit release of a submission if cross submission validation is not success
> CRDCDH-1099

- services/batch-service.js
- services/submission.js
User should not be able to upload data files for a Delete submission
> CRDCDH-1070

- Dockerfile
Modified Dockerfile to add the build use fnl base image
> Modified Dockerfile to add the build use fnl base image

- app.js
- config.js
- resources/yaml/notification_email_values.yaml
- routers/graphql-router.js
- services/notify-user.js
- services/submission.js
- utility/string-util.js
1. fixed global string replacement
2. email template for inactive submission reminder
3. created cronjob for an inactive submission
> CRDCDH-1046

- verifier/submission-verifier.js
- fileValidationStatus ignored for submit action when metadata only submission
> CRDCDH-1197

- Dockerfile
updated the node to node:20.14.0-alpine3.20
> updated the node to node:20.14.0-alpine3.20

- app.js
- config.js
- routers/graphql-router.js
- services/submission.js
- test/graphql-queries/create-submission.test.js
- env datacommons
- removed hard-coded CDS
> CRDCDH-1215

- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/application.js
- services/institution-service.js
- test/services/institution.service.test.js
- test/utility/list.util.test.js
- utility/list-util.js
Add "institutions: [String]" parameter to the approveApplication mutation When an application is approved, if it contains institutions not in the database then add them
> CRDCDH-1128

- app.js
- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/data-record-service.js
- services/submission.js
1. update the validation properties in the submission document.
2. create a new validation collection & store validation object into validation collection.
3. Send validation id when sending SQS.
> CRDCDH-1231

- app.js
- config.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/batch-service.js
- services/data-record-service.js
- services/submission.js
- test/graphql-queries/delete-inactive_submission.test.js
> Implemented crdcdh-1146

- constants/error-constants.js
- services/batch-service.js
- services/data-record-service.js
- services/submission.js
> Implemented 1217

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- services/application.js
- services/approved-studies.js
- services/submission.js
- test/graphql-queries/create-submission.test.js
1. Approved Studies
- stored controlled access property
- directly search & store approved studies into the organization's approved studies
2. saveApplication, approveApplication, createSubmission
- added controlledAccess
3. createSubmission
- replaced studyAbbreviation parameter with a new studyID parameter
> CRDCDH-1295

- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
update/create organization API
- The studyID is used to look up the approved studies in the organization.
> update/create organization API

- resources/yaml/data_file_upload_config.yaml
- services/submission.js
> Crdcdh 1287 001 pgu

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/data-record-service.js
- services/submission.js
1) Implemented crdcdh-1273
2) resolved crdcdh-1321
3) added validation object updating feature if failed to send validation SQS msg.
> Implemented 1273

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/data-record-service.js
- services/submission.js
Implemented crdcdh-1274 for getRelatedNode API
> Crdcdh 1274 001 pgu

- resources/graphql/crdc-datahub.graphql
- services/data-record-service.js
- services/submission.js
Added IDPropName in submissionNodes.
> Crdcdh 1274 002 pgu

- config.js
- constants/error-constants.js
- domain/batch.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/batch-service.js
- services/submission.js
Update createBatch AP:
for data file, it will generate a fileID
> CRDCDH-1288

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- services/data-record-service.js
- services/submission.js
Implemented crdcdh 1330 and 1367, added status and nodeID in getSubmissionNodes
> Crdcdh 1330 001 pgu

- services/data-record-service.js
- total count change; orphaned files(s3) + db file nodes
- data file error; nodes in db + orphaned files(s3)
> CRDCDH-1381

- services/data-record-service.js
The total file record logic is updated.
> Fix stat count

- config.js
- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/aws-request.js
- services/dashboardService.js
aws service added
* quicksight
updated graphql scheme
* dashboard
config
* required dashboardID
* required userID
> CRDCDH-1426

- services/submission.js
add logic to handle the parameter value of "first" is set to -1.
> fixed 1481

- resources/yaml/notification_email_values.yaml
Updated email content for reject email notification
> CRDCDH-1458

- app.js
- middleware/authentication-middleware.js
- resources/graphql/crdc-datahub.graphql
- routers/api-authorization.js
- routers/graphql-router.js
- services/CDEService.js
The getCDEs query is required public without authorization.
> Implemented new service for CDE

- constants/error-constants.js
- constants/submission-constants.js
- services/submission.js
Added character limit to submission name within createSubmission API. 
- Added a 25 character limit to submission name
- Created new error message to reflect this change
[CRDCDH-1544](https://tracker.nci.nih.gov/browse/CRDCDH-1544)
> CRDCDH-1544 Add character limit to name when creating submission

- services/dashboardService.js
allow federal monitor role for getDashboardUrl API
added federal monitor
update driver
> CRDCDH-1508

- routers/api-authorization.js
- routers/graphql-router.js
Enabled authorization for multiple APIs per request.
> Authorization enhancement

- resources/graphql/crdc-datahub.graphql
implemented [CRDCDH-1505](https://tracker.nci.nih.gov/browse/CRDCDH-1505)
BE: API allows assigning Federal Monitor role.
> implemented

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- services/batch-service.js
- services/submission.js
> Implemented task 1506

- services/submission.js
- email notification to the fed monitors
- send the fed monitors in assigned studies
> CRDCDH-1507

- constants/error-constants.js
- services/batch-service.js
- services/submission.js
throw an error when user attempting invalid file names
> CRDCDH-1602

- resources/graphql/crdc-datahub.graphql
- services/application.js
- services/approved-studies.js
1. updating graphql scheme
- PI
- openAccess
2. saveApplication
- accept pi, open access
3. approveApplication
- accept pi, open access
> CRDCDH-1593

- resources/graphql/crdc-datahub.graphql
add archived property in submission type
> updated graphql

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/approved-studies.js
Implemented CRDCDH-1519, 1520 and 1521 for List, Create and Update Approved Study.
> Approved Study

- services/submission.js
The data curator can be retrieved from the associated data-commons, replacing current conincerge email logic
> CRDCDH-1634

- resources/graphql/crdc-datahub.graphql
- services/submission.js
Update listSubmissions API
- filter by name, dbGaPID, dataCommons, submitterName
Update graphql scheme
- dataCommons, submitterNames
> CRDCDH-1622

- services/submission.js
Fix submissionQCResults permission issue for Federal Monitor
> Crdcdh 1506

- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/submission.js
listPotentialCollaborators API
- allow submitter, Org owner, curator and admin roles
- submissions associated with the same study as current submission
> CRDCDH-1661

- resources/graphql/crdc-datahub.graphql
- services/approved-studies.js
1. Fixed controlledAccess filter issue.
2. Update sortDirection default to "ASC".
3. Enabled dbGaPID partial match.
4. Make study and dbGaPID match case-insensitive.
> Crdcdh 1519

- services/submission.js
listSubmissions for the submitter role,
- Submission.submitterID & collaborators.collaboratorID
getSubmission, submissionStats, submissionQCResults, listSubmissionNodeTypes, listBatches, getSubmissionNodes, getNodeDetail, getRelatedNodes
- collaborators "Can View" permission to access
> CRDCDH-1624

- services/approved-studies.js
study abbreviation is not unique
delete duplicate listApprovedStudiesAPI
> CRDCDH-1749

- services/submission.js
> CRDCDH-1623

- routers/graphql-router.js
- services/submission.js
Re-activate inactive submission
> Re-activate inactive submission

- constants/error-constants.js
- services/approved-studies.js
Updated as list below:
1) add study name uniqueness validator for add new approved study.
2) updated regex.
3) updated listApprovedStudies based on new design.
> CRDCDH-1520

- constants/error-constants.js
- services/submission.js
- updated no allowed datacommons error
> CRDCDH-1777

- domain/batch.js
- resources/graphql/crdc-datahub.graphql
- services/batch-service.js
- services/submission.js
Added submitterID and submitterName in batch.
> Implemented CRDCDH-1717

- services/submission.js
> CRDCDH-1755

- services/submission.js
Implemented CRDCDH-1722, Change DCF manifest generation from "Complete" action to "Release" action.
> CRDCDH-1722

- services/submission.js
Enhance the submission history setting.
> hotfix for submission history

- services/submission.js
1.  Add collaborator name and organization.
2. Update the logic to check if the potential collaborator's org has the study.
> Updated per FE for CRDCDH-1662

- services/batch-service.js
- services/submission.js
> Updated FE request CRDCDH-1717

- constants/error-constants.js
> Crdcdh 1622 003 pgu

- constants/error-constants.js
- services/batch-service.js
The user is attempting to mark the uploaded file as a failed upload.
> CRDCDH-1603

- app.js
- routers/graphql-router.js
- services/notify-user.js
- services/user.js
The requestAccess API can create an organization if the provided organization does not exist.
> CRDCDH-1721

- resources/graphql/crdc-datahub.graphql
- services/CDEService.js
Implemented the new requirement for API,  retrieveCDEs.  Please note the other requirements for validator are implemented and have been merged into 3.1.0 in CRDC-Datahub-Validator.
> Crdcdh 1830

- services/CDEService.js
> Hot fix for empty input value

- services/submission.js
added between last, and first name
> added a space

- config.js
> Parsing Hidden Model

- resources/graphql/crdc-datahub.graphql
- services/submission.js
Update listSubmissions API
- added organizations: [Organization],regardless of the pagination. Filtered by all filters except organization ID
> CRDCDH-1870

- services/application.js
This PR depends on Submodule PR https://github.com/CBIIT/crdc-datahub-database-drivers/pull/136 and https://github.com/CBIIT/crdc-datahub-database-drivers/pull/137. See all important details there.
- Refactor BE call to `storeApprovedStudies` and just send the Study ID
- ... All other changes are listed in the above PR
CRDCDH-1853 (bug)
> CRDCDH-1853 Refactor Organization Studies Relationship

- routers/graphql-router.js
retrieve ths study names from the approved studies
> CRDCDH-1885

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/aws-request.js
- services/submission.js
clean up unused APIs
- ListLogs
> CRDCDH-1831

- domain/batch.js
- resources/graphql/crdc-datahub.graphql
- services/batch-service.js
Update createBatch API:
files types to [String!]!
Remove FileInput
> CRDCDH-1835

- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/submission.js
Implemented by move logic in exportSubmission API to SubmissionAction/Release.
> Crdcdh 1837

- services/qc-result-service.js
update the batch filtering to match the filters that are being displayed on the user interface
> update qcresult batch filtering

- services/approved-studies.js
- CRDCDH-1985
- Consolidated study update parameter validation
- trimmed whitespace off of study name and acronym before updating
- prevented acronym from being updated to an empty string or whitespace
- if acronym is not specified when creating a study then the name will be used
> Prevent study acronym from being empty

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- services/application.js
Implemented the task CRDCDH-1997.
> CRDCDH-1997

- resources/graphql/crdc-datahub.graphql
- services/application.js
- services/approved-studies.js
Implemented.  Please merge database driver change first.
> CRDCDH 1999

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- services/submission.js
update createSubmission API
- throw an error if approvedStudy has controlledAccess == true but dbGaPID is empty or null
> CRDCDH-2000

- services/approved-studies.js
allow all registered users to access.
> CRDCDH-2001

- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/user-initialization-service.js
Implemented 1) CRDCDH-2009 and 2) CRDCDH-2060.  These two have overlapped requests and highly related.
> CRDCDH-2009,2060

- resources/graphql/crdc-datahub.graphql
- services/application.js
> CRDCDH 2047

- constants/error-constants.js
- resources/email-templates/notification-template-user.html
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/notify-user.js
- services/user.js
Update requestAccessAPI
- Remove organization parameter
- Add a new studies: [String]!
- Update email contents
> CRDCDH-2012

- resources/graphql/crdc-datahub.graphql
- services/qc-result-service.js
- services/submission.js
- Added issueCode filter to submissionQCResults API
- removed unused submissionQCResults function from previous implementation
> CRDCDH-2003

- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/user-initialization-service.js
Implemented CRDCDH-2009 and 2060 with new designs.
> CRDCH-2009 and 2060

- services/user-initialization-service.js
Updated DB driver reference to use the latest.
> update DB driver reference.

- constants/error-constants.js
- services/data-record-service.js
- services/qc-result-service.js
- services/submission.js
Storing errors in qcResults
- added a code property
- added a severity property
> CRDCDH-2032

- resources/graphql/crdc-datahub.graphql
This is about the permissions and email notification settings for the upcoming sprint. We need to decide how to design the schema.
> permission & email notification graphql schema

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/approved-studies.js
- services/submission.js
Implemented 1) Remove listApprovedStudiesOfMyOrganization API
2) Update createSubmission to verify if studyID parameter is within a user's studies property instead of through organization.
> CRDCDH-2010

- app.js
- constants/error-constants.js
- routers/graphql-router.js
- services/application.js
- services/user.js
**Note: To assist with the PR review, the User in the submodule has only been moved without any modifications.**
Update approveApplication API:
- Store Program(Organization) into organization object.
- Store approved study's ID in user's object.
> CRDCDH-2006

- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/qc-result-service.js
added aggregatedSubmissionQCResults query
> CRDCDH-2002

- constants/error-constants.js
- services/submission.js
- populate the organization object to the Submission object.
- find the organization by the studyID
> CRDCDH-2109

- constants/error-constants.js
- services/dashboardService.js
- verifier/user-info-verifier.js
> CRDCDH 2055 

- resources/graphql/crdc-datahub.graphql
- resources/json/PBACDefaults_config.json
- routers/graphql-router.js
- services/configurationService.js
- services/user.js
> CRDCDH-2121

- constants/submission-constants.js
- resources/graphql/crdc-datahub.graphql
- services/submission.js
- services/user.js
> CRDCDH-2093

- services/user.js
Updated the permissions for the API listActiveCurators, removed user:manage, added study:manage and program: manage
> Fix permission for listActiveCuratorsAPI

- resources/json/PBACDefaults_config.json
1) implemented CRDCDH-2155.
2) updated based on corrected related user stories, CRDCDH-1886, 1887, 1888 and 2022 and the spreadsheets, "Data hub PBAC setting.xlsx
> CRDCDH 2155

- services/application.js
Add permission check for deleteApplication API after CRDCDH-2164 implemented which adding SQ deleting permission..
> Add permission check for deleteApplication API

- constants/error-constants.js
- services/submission.js
> Crdcdh 2156

- services/user.js
All permission/notification can be allowed for any user.
> CRDCDH-2017

- app.js
- config.js
The cron job frequency should read from the DB.
> CRDCDH-1839

- app.js
- config.js
- routers/graphql-router.js
- services/submission.js
The example configuration.
{
"_id": "as_you_wish",
"type": "LIST_OF_S3_BUCKETS",
"SUBMISSION_BUCKET": "test"
}
> DB - Bucket Name & Tier for Data-Model

- services/user.js
- verifier/user-info-verifier.js
Updated verifyPermission to support both permission and array of permissions
> Updated verifyPermission

- constants/application-constants.js
- resources/json/PBACDefaults_config.json
- services/application.js
Added new email for SR, When canceled/restored and reordered.
> Updated based on new requirement

- services/application.js
Updated the logic of valid status in submitApplication API based on new requirement.
> Updated submit SR

- services/submission.js
- verifier/user-info-verifier.js
Remove User Organization check for when a user is creating a submission. User organization is not used anymore
> Remove User Organization Check

- services/submission.js
If the permission verification for listSubmission fails then return an empty list instead of an error
> listsubmission return empty list

- app.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/data-record-service.js
- services/submission.js
Implemented CRDCDH2167 to add an API to retrieve released node.  The PR is replace the PR that caused unresolvable conflicts, https://github.com/CBIIT/crdc-datahub-backend/pull/641
> CRDCDH 2167

- app.js
> CRDCDH-2160

- resources/graphql/crdc-datahub.graphql
- services/application.js
- Added submission request order
- Fixed status typo
- Added canceled status
- Partial Match(study name, submitter name)
> CRDCDH-2162

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- services/data-record-service.js
- services/submission.js
Enhanced RetrieveReleasedData API to meet FE's requirements.
> Hot fix issue

- services/data-record-service.js
make the query works if release.status is string or array of string.
> change the status to string.

- services/notify-user.js
- services/submission.js
Fixed Withdrawl Email notification
> CRDCDH-2114

- services/application.js
Updated the statement in application.js.
> Fix pending condition

- services/user.js
Minor change to rule out string array format.
> Hot fix user ID

- resources/json/PBACDefaults_config.json
updated PBAC default configuration based on user story 2215
> CRDCDH 2215

- services/application.js
Updated based on user story 2284 to auto upgrade the version when save.
> CRDCDH 2253

- services/approved-studies.js
Minor change to fix the issue that createApprovedStudy requires primaryContactID.
> Fixed createApprovedStudy issue.

- services/submission.js
No associated ticket for this change. FE brought up the issue.
> Submitter associated with Study ID

- services/user.js
Fixed the issue in CRDCDH 2307 to add filter, role: Submitter
> CRDCDH 2307

- documentation/3-2-0/Users Migration.yaml
- services/qc-result-service.js
- updates to validation results severity filter
- fix misplaced quotation in "Set Federal Leads Permissions" command
> Fix severity filter (1637)

- services/application.js
Remove auto upgrade logic in submitApplication API.
> fixed CRDCDH 2455

- documentation/3-2-0/Users Migration.yaml
- resources/json/PBACDefaults_config.json
- services/configurationService.js
- services/user.js
1. attached migration script.
2. updated PBAC json file for inherited properties.
3. added the inherited permissions to user document.
> CRDCDH-2437

- services/submission.js
remove SQS message, GENERATE_DCF_MANIFEST
> CRDCDH-2504

- services/submission.js
Update delete data record API
- it affects the data file size.
> CRDCDH-2432

- documentation/3-3-0/restoreUserNotifications.js
- resources/json/PBACDefaults_config.json
replaced all access_change to access_changed
> CRDCDH-2439

- services/application.js
> CRDCDH-2434

- services/configurationService.js
Minor change to remove permission verification and allow all login user to retrieve default PBAC configurations.
> Crdcdh 2510

- constants/error-constants.js
- services/batch-service.js
- services/submission.js
Set proper error if user interrupted uploading from CLI.
> CRDCDH-2435

- resources/graphql/crdc-datahub.graphql
- services/user.js
> CRDCDH-2487

- services/batch-service.js
- services/s3-service.js
- services/submission.js
updated the download file name
> Crdcdh 2483

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/institution-service.js
- services/user.js
Created updateInstitution/getInstitution APIs
> CRDCDH-2486

- services/submission.js
Updated the function,  #ProcessSubmissionNodes(result, IDPropName=null),  to fix the issue in the ticket
> CRDCDH-2523

- services/application.js
note: no longer store a new study using the organization in the application document.
> CRDCDH-2569

- constants/error-constants.js
- constants/permission-scope-constants.js
- resources/json/PBACDefaults_config.json
- routers/graphql-router.js
- services/authorization-service.js
- test/services/authorization.service.test.js
Added a central authorization service to check scopes Added scopes to the Federal Lead entries in PBACDefaults.json as examples
> Authorization Service

- resources/json/PBACDefaults_config.json
Updated based on the role and score spreadsheet.
> CRDCDH-2664

- services/submission.js
> CRDCDH-2614

- resources/json/PBACDefaults_config.json
> Crdcdh 2672

- services/approved-studies.js
Implemented.
1) updated addApprovedStudyAPI function to insert new studyID into "NA" organization.studies.
> Crdcdh 2616 

- constants/error-constants.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/user.js
Implemented task CRDCDH-2627.
Add new API, userIsPrimaryContact(userID: ID!): Boolean
> Crdcdh 2627

- documentation/3-3-0/removeDefaultPBACForFederalLeader.js
> reset Fl PBAC

- resources/email-templates/notification-template-submission.html
> CRDCDH-2738

- documentation/3-3-0/removeDefaultPBACForFederalLeader.js
> reset FL notifications

- services/application.js
Set default programName to "NA" when approve a SR without program.
> Crdcdh 2616

- app.js
> Set the max request size

- documentation/3-3-0/CRDCDH-2663.js
- resources/graphql/crdc-datahub.graphql
- services/approved-studies.js
- services/submission.js
> CRDCDH-2713

- constants/error-constants.js
- services/batch-service.js
> CRDCDH-2837

- services/data-record-service.js
> CRDCDH 2890

- resources/json/PBACDefaults_config.json
> CRDCDH 2811

- documentation/3-3-0/CRDCDH-2663.js
The organization property is no longer stored within the submission. The study is not associated with any program, they should assign to the NA program
> Unlinking Organization

- resources/graphql/crdc-datahub.graphql
- services/release-service.js
> CRDCDH-2810

- resources/json/PBACDefaults_config.json
Implemented CRDCDH-2966 by adding a new notification configuration for all roles in the PBAC default json file.
> CRDCDH-2966

- resources/graphql/crdc-datahub.graphql
- services/application.js
- test/services/release-study.service.test.js
- test/services/submission-request.test.js
updated approvedApplication(pendingModelChange flag), getApplication, listApplication
> CRDCDH-2942

- constants/error-constants.js
- services/data-record-service.js
- services/submission.js
- utility/io-util.js
Hot fix for dbGap sheet if no participant or sample found.
> Hot fix for dbGap sheet

- dao/pendingPV.js
- services/submission.js
> CRDCDH-2930

- services/data-record-service.js
> updated DS name

- services/data-record-service.js
Add underscore after dbGap per request.
> Update dbPap sheet name

- test/services/submission.getUploaderCLIConfig.test.js
fix tests for getUploaderCLIConfigs
> fix tests for getUploaderCLIConfigs

- constants/error-constants.js
- services/data-record-service.js
Updated the subject ID in SubjectSampleMap.ts
> CRDCDH 3001

- constants/error-constants.js
- package-lock.json
- package.json
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/configurationService.js
- test/services/configurationService.getApplicationFromVersion.test.js
Add API to return APPLICATION_FORM_VERSIONS configuration
> CRDCDH-3132

- services/application.js
Migrat $regex to PRISMA filter
> CRDCDH 3102

- services/data-record-service.js
Reset no tumor status from 0 to 2
> CRDCDH 3148

- services/application.js
Use data fields as query parameters.
> CRDCDH 3054

- resources/graphql/crdc-datahub.graphql
- services/release-service.js
Add required parameter, dataCommonsDisplayName, to the API, downloadAllReleasedNodes(studyID: String!, dataCommonsDisplayName: String!) : String
> CRDCDH 3055

- dao/approvedStudy.js
- dao/institution.js
- services/release-service.js
- utility/string-util.js
> CRDCDH-3144

- documentation/3-4-0/setEntityTypeValueInRelease.js
- resources/graphql/crdc-datahub.graphql
- routers/graphql-router.js
- services/data-record-service.js
- services/submission.js
- test/services/data-record-service.test.js
- test/services/submission.getSubmissionSummary.test.js
Implemented CRDCDH-3055, new API to get submission summary
> Crdcdh 3055 001 pgu

- .github/workflows/build-be.yml
> added a step to the unit test

- .github/workflows/build-be.yml.b4pr
> added a step when PR is merged will trigger a build
